[workspace]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
name = "mujoco-rs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.89.0,<1.90"
gcc = ">=15.1.0,<15.2"
gxx = ">=15.1.0,<15.2"
