//! Auto-generated Data functions
//! Generated by generate_from_introspect.py - DO NOT EDIT MANUALLY

use crate::Data;
pub fn mj_step(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_step(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_step1(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_step1(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_step2(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_step2(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_forward(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_forward(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_inverse(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_inverse(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_reset_data(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_resetData(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_fwd_position(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_fwdPosition(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_fwd_velocity(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_fwdVelocity(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_fwd_actuation(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_fwdActuation(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_fwd_acceleration(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_fwdAcceleration(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_fwd_constraint(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_fwdConstraint(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_euler(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_Euler(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_implicit(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_implicit(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_inv_position(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_invPosition(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_inv_velocity(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_invVelocity(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_inv_constraint(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_invConstraint(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_compare_fwd_inv(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_compareFwdInv(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_sensor_pos(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_sensorPos(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_sensor_vel(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_sensorVel(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_sensor_acc(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_sensorAcc(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_energy_pos(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_energyPos(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_energy_vel(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_energyVel(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_check_pos(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_checkPos(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_check_vel(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_checkVel(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_check_acc(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_checkAcc(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_kinematics(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_kinematics(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_com_pos(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_comPos(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_camlight(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_camlight(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_flex(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_flex(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_tendon(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_tendon(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_transmission(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_transmission(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_crb(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_crb(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_make_m(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_makeM(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_factor_m(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_factorM(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_com_vel(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_comVel(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_passive(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_passive(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_subtree_vel(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_subtreeVel(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_rne_post_constraint(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_rnePostConstraint(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_collision(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_collision(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_make_constraint(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_makeConstraint(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_island(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_island(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_project_constraint(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_projectConstraint(data.model.as_ptr(), data.as_mut_ptr());
    }
}
pub fn mj_reference_constraint(data: &mut Data) {
    unsafe {
        mujoco_sys::mj_referenceConstraint(data.model.as_ptr(), data.as_mut_ptr());
    }
}
