//! Auto-generated math utility functions
//! Generated by generate_from_introspect.py - DO NOT EDIT MANUALLY

#![allow(non_snake_case)]

/// Intersect ray with pure geom, return nearest distance or -1 if no intersection.
pub fn mju_ray_geom(
    pos: &[f64; 3],
    mat: &[f64; 9],
    size: &[f64; 3],
    pnt: &[f64; 3],
    vec: &[f64; 3],
    geomtype: i32,
) -> f64 {
    unsafe {
        mujoco_sys::mju_rayGeom(
            pos.as_ptr(),
            mat.as_ptr(),
            size.as_ptr(),
            pnt.as_ptr(),
            vec.as_ptr(),
            geomtype,
        )
    }
}

/// Set res = 0.
pub fn mju_zero3(res: &mut [f64; 3]) {
    unsafe {
        mujoco_sys::mju_zero3(res.as_mut_ptr());
    }
}

/// Set res = vec.
pub fn mju_copy3(data: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_copy3(res.as_mut_ptr(), data.as_ptr());
    }
    res
}

/// Set res = vec*scl.
pub fn mju_scl3(vec: &[f64; 3], scl: f64) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_scl3(res.as_mut_ptr(), vec.as_ptr(), scl);
    }
    res
}

/// Set res = vec1 + vec2.
pub fn mju_add3(vec1: &[f64; 3], vec2: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_add3(res.as_mut_ptr(), vec1.as_ptr(), vec2.as_ptr());
    }
    res
}

/// Set res = vec1 - vec2.
pub fn mju_sub3(vec1: &[f64; 3], vec2: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_sub3(res.as_mut_ptr(), vec1.as_ptr(), vec2.as_ptr());
    }
    res
}

/// Set res = res + vec.
pub fn mju_add_to3(vec: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_addTo3(res.as_mut_ptr(), vec.as_ptr());
    }
    res
}

/// Set res = res - vec.
pub fn mju_sub_from3(vec: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_subFrom3(res.as_mut_ptr(), vec.as_ptr());
    }
    res
}

/// Set res = res + vec*scl.
pub fn mju_add_to_scl3(vec: &[f64; 3], scl: f64) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_addToScl3(res.as_mut_ptr(), vec.as_ptr(), scl);
    }
    res
}

/// Set res = vec1 + vec2*scl.
pub fn mju_add_scl3(vec1: &[f64; 3], vec2: &[f64; 3], scl: f64) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_addScl3(res.as_mut_ptr(), vec1.as_ptr(), vec2.as_ptr(), scl);
    }
    res
}

/// Normalize vector, return length before normalization.
pub fn mju_normalize3(vec: &mut [f64; 3]) -> f64 {
    unsafe { mujoco_sys::mju_normalize3(vec.as_mut_ptr()) }
}

/// Return vector length (without normalizing the vector).
pub fn mju_norm3(vec: &[f64; 3]) -> f64 {
    unsafe { mujoco_sys::mju_norm3(vec.as_ptr()) }
}

/// Return dot-product of vec1 and vec2.
pub fn mju_dot3(vec1: &[f64; 3], vec2: &[f64; 3]) -> f64 {
    unsafe { mujoco_sys::mju_dot3(vec1.as_ptr(), vec2.as_ptr()) }
}

/// Return Cartesian distance between 3D vectors pos1 and pos2.
pub fn mju_dist3(pos1: &[f64; 3], pos2: &[f64; 3]) -> f64 {
    unsafe { mujoco_sys::mju_dist3(pos1.as_ptr(), pos2.as_ptr()) }
}

/// Multiply 3-by-3 matrix by vector: res = mat * vec.
pub fn mju_mul_mat_vec3(mat: &[f64; 9], vec: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_mulMatVec3(res.as_mut_ptr(), mat.as_ptr(), vec.as_ptr());
    }
    res
}

/// Multiply transposed 3-by-3 matrix by vector: res = mat' * vec.
pub fn mju_mul_mat_t_vec3(mat: &[f64; 9], vec: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_mulMatTVec3(res.as_mut_ptr(), mat.as_ptr(), vec.as_ptr());
    }
    res
}

/// Compute cross-product: res = cross(a, b).
pub fn mju_cross(a: &[f64; 3], b: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_cross(res.as_mut_ptr(), a.as_ptr(), b.as_ptr());
    }
    res
}

/// Set res = 0.
pub fn mju_zero4(res: &mut [f64; 4]) {
    unsafe {
        mujoco_sys::mju_zero4(res.as_mut_ptr());
    }
}

/// Set res = (1,0,0,0).
pub fn mju_unit4(res: &mut [f64; 4]) {
    unsafe {
        mujoco_sys::mju_unit4(res.as_mut_ptr());
    }
}

/// Set res = vec.
pub fn mju_copy4(data: &[f64; 4]) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_copy4(res.as_mut_ptr(), data.as_ptr());
    }
    res
}

/// Normalize vector, return length before normalization.
pub fn mju_normalize4(vec: &mut [f64; 4]) -> f64 {
    unsafe { mujoco_sys::mju_normalize4(vec.as_mut_ptr()) }
}

/// Set res = 0.
pub fn mju_zero(res: &mut [f64], n: i32) {
    unsafe {
        mujoco_sys::mju_zero(res.as_mut_ptr(), n);
    }
}

/// Set res = val.
pub fn mju_fill(res: &mut [f64], val: f64, n: i32) {
    unsafe {
        mujoco_sys::mju_fill(res.as_mut_ptr(), val, n);
    }
}

/// Set res = vec.
pub fn mju_copy(res: &mut [f64], vec: &[f64], n: i32) {
    unsafe {
        mujoco_sys::mju_copy(res.as_mut_ptr(), vec.as_ptr(), n);
    }
}

/// Return sum(vec).
pub fn mju_sum(vec: &[f64], n: i32) -> f64 {
    unsafe { mujoco_sys::mju_sum(vec.as_ptr(), n) }
}

/// Return L1 norm: sum(abs(vec)).
pub fn mju_l1(vec: &[f64], n: i32) -> f64 {
    unsafe { mujoco_sys::mju_L1(vec.as_ptr(), n) }
}

/// Set res = vec*scl.
pub fn mju_scl(res: &mut [f64], vec: &[f64], scl: f64, n: i32) {
    unsafe {
        mujoco_sys::mju_scl(res.as_mut_ptr(), vec.as_ptr(), scl, n);
    }
}

/// Set res = vec1 + vec2.
pub fn mju_add(res: &mut [f64], vec1: &[f64], vec2: &[f64], n: i32) {
    unsafe {
        mujoco_sys::mju_add(res.as_mut_ptr(), vec1.as_ptr(), vec2.as_ptr(), n);
    }
}

/// Set res = vec1 - vec2.
pub fn mju_sub(res: &mut [f64], vec1: &[f64], vec2: &[f64], n: i32) {
    unsafe {
        mujoco_sys::mju_sub(res.as_mut_ptr(), vec1.as_ptr(), vec2.as_ptr(), n);
    }
}

/// Set res = res + vec.
pub fn mju_add_to(res: &mut [f64], vec: &[f64], n: i32) {
    unsafe {
        mujoco_sys::mju_addTo(res.as_mut_ptr(), vec.as_ptr(), n);
    }
}

/// Set res = res - vec.
pub fn mju_sub_from(res: &mut [f64], vec: &[f64], n: i32) {
    unsafe {
        mujoco_sys::mju_subFrom(res.as_mut_ptr(), vec.as_ptr(), n);
    }
}

/// Set res = res + vec*scl.
pub fn mju_add_to_scl(res: &mut [f64], vec: &[f64], scl: f64, n: i32) {
    unsafe {
        mujoco_sys::mju_addToScl(res.as_mut_ptr(), vec.as_ptr(), scl, n);
    }
}

/// Set res = vec1 + vec2*scl.
pub fn mju_add_scl(res: &mut [f64], vec1: &[f64], vec2: &[f64], scl: f64, n: i32) {
    unsafe {
        mujoco_sys::mju_addScl(res.as_mut_ptr(), vec1.as_ptr(), vec2.as_ptr(), scl, n);
    }
}

/// Normalize vector, return length before normalization.
pub fn mju_normalize(res: &mut [f64], n: i32) -> f64 {
    unsafe { mujoco_sys::mju_normalize(res.as_mut_ptr(), n) }
}

/// Return vector length (without normalizing vector).
pub fn mju_norm(res: &[f64], n: i32) -> f64 {
    unsafe { mujoco_sys::mju_norm(res.as_ptr(), n) }
}

/// Return dot-product of vec1 and vec2.
pub fn mju_dot(vec1: &[f64], vec2: &[f64], n: i32) -> f64 {
    unsafe { mujoco_sys::mju_dot(vec1.as_ptr(), vec2.as_ptr(), n) }
}

/// Multiply matrix and vector: res = mat * vec.
pub fn mju_mul_mat_vec(res: &mut [f64], mat: &[f64], vec: &[f64], nr: i32, nc: i32) {
    unsafe {
        mujoco_sys::mju_mulMatVec(res.as_mut_ptr(), mat.as_ptr(), vec.as_ptr(), nr, nc);
    }
}

/// Multiply transposed matrix and vector: res = mat' * vec.
pub fn mju_mul_mat_t_vec(res: &mut [f64], mat: &[f64], vec: &[f64], nr: i32, nc: i32) {
    unsafe {
        mujoco_sys::mju_mulMatTVec(res.as_mut_ptr(), mat.as_ptr(), vec.as_ptr(), nr, nc);
    }
}

/// Multiply square matrix with vectors on both sides: returns vec1' * mat * vec2.
pub fn mju_mul_vec_mat_vec(vec1: &[f64], mat: &[f64], vec2: &[f64], n: i32) -> f64 {
    unsafe { mujoco_sys::mju_mulVecMatVec(vec1.as_ptr(), mat.as_ptr(), vec2.as_ptr(), n) }
}

/// Transpose matrix: res = mat'.
pub fn mju_transpose(res: &mut [f64], mat: &[f64], nr: i32, nc: i32) {
    unsafe {
        mujoco_sys::mju_transpose(res.as_mut_ptr(), mat.as_ptr(), nr, nc);
    }
}

/// Symmetrize square matrix res = (mat + mat')/2.
pub fn mju_symmetrize(res: &mut [f64], mat: &[f64], n: i32) {
    unsafe {
        mujoco_sys::mju_symmetrize(res.as_mut_ptr(), mat.as_ptr(), n);
    }
}

/// Set mat to the identity matrix.
pub fn mju_eye(mat: &mut [f64], n: i32) {
    unsafe {
        mujoco_sys::mju_eye(mat.as_mut_ptr(), n);
    }
}

/// Multiply matrices: res = mat1 * mat2.
pub fn mju_mul_mat_mat(res: &mut [f64], mat1: &[f64], mat2: &[f64], r1: i32, c1: i32, c2: i32) {
    unsafe {
        mujoco_sys::mju_mulMatMat(res.as_mut_ptr(), mat1.as_ptr(), mat2.as_ptr(), r1, c1, c2);
    }
}

/// Multiply matrices, second argument transposed: res = mat1 * mat2'.
pub fn mju_mul_mat_mat_t(res: &mut [f64], mat1: &[f64], mat2: &[f64], r1: i32, c1: i32, r2: i32) {
    unsafe {
        mujoco_sys::mju_mulMatMatT(res.as_mut_ptr(), mat1.as_ptr(), mat2.as_ptr(), r1, c1, r2);
    }
}

/// Multiply matrices, first argument transposed: res = mat1' * mat2.
pub fn mju_mul_mat_t_mat(res: &mut [f64], mat1: &[f64], mat2: &[f64], r1: i32, c1: i32, c2: i32) {
    unsafe {
        mujoco_sys::mju_mulMatTMat(res.as_mut_ptr(), mat1.as_ptr(), mat2.as_ptr(), r1, c1, c2);
    }
}

/// Set res = mat' * diag * mat if diag is not NULL, and res = mat' * mat otherwise.
pub fn mju_sqr_mat_t_d(res: &mut [f64], mat: &[f64], diag: &[f64], nr: i32, nc: i32) {
    unsafe {
        mujoco_sys::mju_sqrMatTD(res.as_mut_ptr(), mat.as_ptr(), diag.as_ptr(), nr, nc);
    }
}

/// Coordinate transform of 6D motion or force vector in rotation:translation format. rotnew2old is 3-by-3, NULL means no rotation; flg_force specifies force or motion type.
pub fn mju_transform_spatial(
    vec: &[f64; 6],
    flg_force: i32,
    newpos: &[f64; 3],
    oldpos: &[f64; 3],
    rotnew2old: &[f64; 9],
) -> [f64; 6] {
    let mut res = [0.0; 6];
    unsafe {
        mujoco_sys::mju_transformSpatial(
            res.as_mut_ptr(),
            vec.as_ptr(),
            flg_force,
            newpos.as_ptr(),
            oldpos.as_ptr(),
            rotnew2old.as_ptr(),
        );
    }
    res
}

/// Rotate vector by quaternion.
pub fn mju_rot_vec_quat(vec: &[f64; 3], quat: &[f64; 4]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_rotVecQuat(res.as_mut_ptr(), vec.as_ptr(), quat.as_ptr());
    }
    res
}

/// Conjugate quaternion, corresponding to opposite rotation.
pub fn mju_neg_quat(quat: &[f64; 4]) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_negQuat(res.as_mut_ptr(), quat.as_ptr());
    }
    res
}

/// Multiply quaternions.
pub fn mju_mul_quat(quat1: &[f64; 4], quat2: &[f64; 4]) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_mulQuat(res.as_mut_ptr(), quat1.as_ptr(), quat2.as_ptr());
    }
    res
}

/// Multiply quaternion and axis.
pub fn mju_mul_quat_axis(quat: &[f64; 4], axis: &[f64; 3]) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_mulQuatAxis(res.as_mut_ptr(), quat.as_ptr(), axis.as_ptr());
    }
    res
}

/// Convert axisAngle to quaternion.
pub fn mju_axis_angle2quat(axis: &[f64; 3], angle: f64) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_axisAngle2Quat(res.as_mut_ptr(), axis.as_ptr(), angle);
    }
    res
}

/// Convert quaternion (corresponding to orientation difference) to 3D velocity.
pub fn mju_quat2vel(quat: &[f64; 4], dt: f64) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_quat2Vel(res.as_mut_ptr(), quat.as_ptr(), dt);
    }
    res
}

/// Subtract quaternions, express as 3D velocity: qb*quat(res) = qa.
pub fn mju_sub_quat(qa: &[f64; 4], qb: &[f64; 4]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_subQuat(res.as_mut_ptr(), qa.as_ptr(), qb.as_ptr());
    }
    res
}

/// Convert quaternion to 3D rotation matrix.
pub fn mju_quat2mat(quat: &[f64; 4]) -> [f64; 9] {
    let mut res = [0.0; 9];
    unsafe {
        mujoco_sys::mju_quat2Mat(res.as_mut_ptr(), quat.as_ptr());
    }
    res
}

/// Convert 3D rotation matrix to quaternion.
pub fn mju_mat2quat(mat: &[f64; 9]) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_mat2Quat(res.as_mut_ptr(), mat.as_ptr());
    }
    res
}

/// Compute time-derivative of quaternion, given 3D rotational velocity.
pub fn mju_deriv_quat(quat: &[f64; 4], vel: &[f64; 3]) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_derivQuat(res.as_mut_ptr(), quat.as_ptr(), vel.as_ptr());
    }
    res
}

/// Integrate quaternion given 3D angular velocity.
pub fn mju_quat_integrate(quat: &mut [f64; 4], vel: &[f64; 3], scale: f64) {
    unsafe {
        mujoco_sys::mju_quatIntegrate(quat.as_mut_ptr(), vel.as_ptr(), scale);
    }
}

/// Construct quaternion performing rotation from z-axis to given vector.
pub fn mju_quat_z2vec(vec: &[f64; 3]) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_quatZ2Vec(res.as_mut_ptr(), vec.as_ptr());
    }
    res
}

/// Extract 3D rotation from an arbitrary 3x3 matrix by refining the input quaternion. Returns the number of iterations required to converge
pub fn mju_mat2rot(mat: &[f64; 9]) -> ([f64; 4], i32) {
    let mut res = [0.0; 4];
    let ret = unsafe { mujoco_sys::mju_mat2Rot(res.as_mut_ptr(), mat.as_ptr()) };
    (res, ret)
}

/// Convert sequence of Euler angles (radians) to quaternion. seq[0,1,2] must be in 'xyzXYZ', lower/upper-case mean intrinsic/extrinsic rotations.
pub fn mju_euler2quat(euler: &[f64; 3], seq: &str) -> [f64; 4] {
    let mut res = [0.0; 4];
    unsafe {
        mujoco_sys::mju_euler2Quat(
            res.as_mut_ptr(),
            euler.as_ptr(),
            std::ffi::CString::new(seq).unwrap().as_ptr(),
        );
    }
    res
}

/// Multiply two poses.
pub fn mju_mul_pose(
    quatres: &mut [f64; 4],
    pos1: &[f64; 3],
    quat1: &[f64; 4],
    pos2: &[f64; 3],
    quat2: &[f64; 4],
) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_mulPose(
            res.as_mut_ptr(),
            quatres.as_mut_ptr(),
            pos1.as_ptr(),
            quat1.as_ptr(),
            pos2.as_ptr(),
            quat2.as_ptr(),
        );
    }
    res
}

/// Conjugate pose, corresponding to the opposite spatial transformation.
pub fn mju_neg_pose(quatres: &mut [f64; 4], pos: &[f64; 3], quat: &[f64; 4]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_negPose(
            res.as_mut_ptr(),
            quatres.as_mut_ptr(),
            pos.as_ptr(),
            quat.as_ptr(),
        );
    }
    res
}

/// Transform vector by pose.
pub fn mju_trn_vec_pose(pos: &[f64; 3], quat: &[f64; 4], vec: &[f64; 3]) -> [f64; 3] {
    let mut res = [0.0; 3];
    unsafe {
        mujoco_sys::mju_trnVecPose(res.as_mut_ptr(), pos.as_ptr(), quat.as_ptr(), vec.as_ptr());
    }
    res
}

/// Cholesky decomposition: mat = L*L'; return rank, decomposition performed in-place into mat.
pub fn mju_chol_factor(mat: &mut [f64], n: i32, mindiag: f64) -> i32 {
    unsafe { mujoco_sys::mju_cholFactor(mat.as_mut_ptr(), n, mindiag) }
}

/// Solve (mat*mat') * res = vec, where mat is a Cholesky factor.
pub fn mju_chol_solve(res: &mut [f64], mat: &[f64], vec: &[f64], n: i32) {
    unsafe {
        mujoco_sys::mju_cholSolve(res.as_mut_ptr(), mat.as_ptr(), vec.as_ptr(), n);
    }
}

/// Cholesky rank-one update: L*L' +/- x*x'; return rank.
pub fn mju_chol_update(mat: &mut [f64], x: &mut [f64], n: i32, flg_plus: i32) -> i32 {
    unsafe { mujoco_sys::mju_cholUpdate(mat.as_mut_ptr(), x.as_mut_ptr(), n, flg_plus) }
}

/// Band-dense Cholesky decomposition.  Returns minimum value in the factorized diagonal, or 0 if rank-deficient.  mat has (ntotal-ndense) x nband + ndense x ntotal elements.  The first (ntotal-ndense) x nband store the band part, left of diagonal, inclusive.  The second ndense x ntotal store the band part as entire dense rows.  Add diagadd+diagmul*mat_ii to diagonal before factorization.
pub fn mju_chol_factor_band(
    mat: &mut [f64],
    ntotal: i32,
    nband: i32,
    ndense: i32,
    diagadd: f64,
    diagmul: f64,
) -> f64 {
    unsafe {
        mujoco_sys::mju_cholFactorBand(mat.as_mut_ptr(), ntotal, nband, ndense, diagadd, diagmul)
    }
}

/// Solve (mat*mat')*res = vec where mat is a band-dense Cholesky factor.
pub fn mju_chol_solve_band(
    res: &mut [f64],
    mat: &[f64],
    vec: &[f64],
    ntotal: i32,
    nband: i32,
    ndense: i32,
) {
    unsafe {
        mujoco_sys::mju_cholSolveBand(
            res.as_mut_ptr(),
            mat.as_ptr(),
            vec.as_ptr(),
            ntotal,
            nband,
            ndense,
        );
    }
}

/// Convert banded matrix to dense matrix, fill upper triangle if flg_sym>0.
pub fn mju_band2dense(
    res: &mut [f64],
    mat: &[f64],
    ntotal: i32,
    nband: i32,
    ndense: i32,
    flg_sym: u8,
) {
    unsafe {
        mujoco_sys::mju_band2Dense(
            res.as_mut_ptr(),
            mat.as_ptr(),
            ntotal,
            nband,
            ndense,
            flg_sym,
        );
    }
}

/// Convert dense matrix to banded matrix.
pub fn mju_dense2band(res: &mut [f64], mat: &[f64], ntotal: i32, nband: i32, ndense: i32) {
    unsafe {
        mujoco_sys::mju_dense2Band(res.as_mut_ptr(), mat.as_ptr(), ntotal, nband, ndense);
    }
}

/// Multiply band-diagonal matrix with nvec vectors, include upper triangle if flg_sym>0.
pub fn mju_band_mul_mat_vec(
    res: &mut [f64],
    mat: &[f64],
    vec: &[f64],
    ntotal: i32,
    nband: i32,
    ndense: i32,
    nvec: i32,
    flg_sym: u8,
) {
    unsafe {
        mujoco_sys::mju_bandMulMatVec(
            res.as_mut_ptr(),
            mat.as_ptr(),
            vec.as_ptr(),
            ntotal,
            nband,
            ndense,
            nvec,
            flg_sym,
        );
    }
}

/// Address of diagonal element i in band-dense matrix representation.
pub fn mju_band_diag(i: i32, ntotal: i32, nband: i32, ndense: i32) -> i32 {
    unsafe { mujoco_sys::mju_bandDiag(i, ntotal, nband, ndense) }
}

/// Eigenvalue decomposition of symmetric 3x3 matrix, mat = eigvec * diag(eigval) * eigvec'.
pub fn mju_eig3(eigvec: &mut [f64; 9], quat: &mut [f64; 4], mat: &[f64; 9]) -> ([f64; 3], i32) {
    let mut res = [0.0; 3];
    let ret = unsafe {
        mujoco_sys::mju_eig3(
            res.as_mut_ptr(),
            eigvec.as_mut_ptr(),
            quat.as_mut_ptr(),
            mat.as_ptr(),
        )
    };
    (res, ret)
}

/// Return min(a,b) with single evaluation of a and b.
pub fn mju_min(a: f64, b: f64) -> f64 {
    unsafe { mujoco_sys::mju_min(a, b) }
}

/// Return max(a,b) with single evaluation of a and b.
pub fn mju_max(a: f64, b: f64) -> f64 {
    unsafe { mujoco_sys::mju_max(a, b) }
}

/// Return sign of x: +1, -1 or 0.
pub fn mju_sign(x: f64) -> f64 {
    unsafe { mujoco_sys::mju_sign(x) }
}

/// Round x to nearest integer.
pub fn mju_round(x: f64) -> i32 {
    unsafe { mujoco_sys::mju_round(x) }
}

/// Construct a warning message given the warning type and info.
pub fn mju_warning_text(warning: i32, info: usize) {
    unsafe {
        mujoco_sys::mju_warningText(warning, info);
    }
}

/// Return 1 if nan or abs(x)>mjMAXVAL, 0 otherwise. Used by check functions.
pub fn mju_is_bad(x: f64) -> i32 {
    unsafe { mujoco_sys::mju_isBad(x) }
}

/// Return 1 if all elements are 0.
pub fn mju_is_zero(vec: &mut [f64], n: i32) -> i32 {
    unsafe { mujoco_sys::mju_isZero(vec.as_mut_ptr(), n) }
}

/// Generate Halton sequence.
pub fn mju_halton(index: i32, base: i32) -> f64 {
    unsafe { mujoco_sys::mju_Halton(index, base) }
}

/// Sigmoid function over 0<=x<=1 using quintic polynomial.
pub fn mju_sigmoid(x: f64) -> f64 {
    unsafe { mujoco_sys::mju_sigmoid(x) }
}

/// Derivatives of mju_subQuat.
pub fn mjd_sub_quat(qa: &[f64; 4], qb: &[f64; 4], Da: &mut [f64; 9], Db: &mut [f64; 9]) {
    unsafe {
        mujoco_sys::mjd_subQuat(qa.as_ptr(), qb.as_ptr(), Da.as_mut_ptr(), Db.as_mut_ptr());
    }
}

/// Derivatives of mju_quatIntegrate.
pub fn mjd_quat_integrate(
    vel: &[f64; 3],
    scale: f64,
    Dquat: &mut [f64; 9],
    Dvel: &mut [f64; 9],
    Dscale: &mut [f64; 3],
) {
    unsafe {
        mujoco_sys::mjd_quatIntegrate(
            vel.as_ptr(),
            scale,
            Dquat.as_mut_ptr(),
            Dvel.as_mut_ptr(),
            Dscale.as_mut_ptr(),
        );
    }
}
