//! Math type aliases using nalgebra
//! Generated by generate_from_introspect.py - DO NOT EDIT MANUALLY

pub use nalgebra::{
    DMatrix, DVector, Isometry3, Matrix3, Matrix3xX, Matrix4, Matrix6xX, MatrixXx3, MatrixXx6,
    Quaternion, Rotation3, UnitQuaternion, Vector3, Vector4, Vector6,
};

/// 3D vector (position, velocity, etc.)
pub type Vec3 = Vector3<f64>;

/// 4D vector
pub type Vec4 = Vector4<f64>;

/// 6D vector (spatial velocity, wrench, etc.)
pub type Vec6 = Vector6<f64>;

/// 3x3 matrix (rotation, inertia, etc.)
pub type Mat3 = Matrix3<f64>;

/// 4x4 matrix (homogeneous transform)
pub type Mat4 = Matrix4<f64>;

/// Unit quaternion (orientation)
pub type Quat = UnitQuaternion<f64>;

/// 6D pose (position + orientation)
pub type Pose = Isometry3<f64>;

/// 3×nv Jacobian matrix (position or rotation Jacobian)
pub type Jacobian3xN = Matrix3xX<f64>;

/// 6×nv Jacobian matrix (combined position + rotation Jacobian)
pub type Jacobian6xN = Matrix6xX<f64>;

/// nv×6 transposed Jacobian (internal, for row-major FFI conversion)
pub(crate) type JacobianNx6 = MatrixXx6<f64>;

/// nv×3 transposed Jacobian (internal, for row-major FFI conversion)
pub(crate) type JacobianNx3 = MatrixXx3<f64>;
